{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hansehe-devblog.serviceAccountName" . }}
  labels:
{{ include "hansehe-devblog.labels" . | nindent 4 }}
{{- end -}}
