apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: devblog
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: devblog
          servicePort: 80