{
 "title": "Nginx Stats",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "rate_interval", "query": "10h" },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"nginx-exporter:9113\",job=\"nginx-exporter\"}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 19, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nginx_connections_active", "legendFormat": "active" },
    { "expr": "nginx_connections_reading", "legendFormat": "reading" },
    { "expr": "nnginx_connections_waiting", "legendFormat": "waiting" },
    { "expr": "nginx_connections_writing", "legendFormat": "writing" }
   ]
  },
  {
   "title": "Rate Of Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$rate_interval])",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Rate Of Accepted & Handled Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted[$rate_interval])",
     "legendFormat": "connections accepted"
    },
    {
     "expr": "rate(nginx_connections_handled[$rate_interval])",
     "legendFormat": "connections handled"
    }
   ]
  }
 ]
}