version: '3'

services:
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:0.2.0
    hostname: nginx-exporter
    networks:
      - backend_network
    environment:
      - nginx.scrape-uri:http://nginx-dev-blog:8080/stub_status

networks:
  backend_network:
    external: true