version: '3.2'

services:
  prometheus:
    image: hansehe/prometheus-dev-blog:${VERSION}
    hostname: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    networks:
      - backend_network
    ports:
        - 9090:9090

networks:
  backend_network:
    external: true