version: '3.2'

services:
  nginx:
    image: hansehe/nginx-dev-blog:${VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend_network
    # volumes:
    #   - certbot_conf:/etc/letsencrypt
    #   - certbot_www:/var/www/certbot
    ports:
      - 8080:80
      - 444:443
      # - 3000:3000
      # - 9090:9090
      # - 15672:15672
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

networks:
  backend_network:
    external: true

# volumes:
#   certbot_conf:
#     external: true
#   certbot_www:
#     external: true