global:
    scrape_interval: 5s
    external_labels:
        monitor: 'nginx-monitor'
scrape_configs:
    - job_name: 'nginx-exporter'
      static_configs:
          - targets: ['nginx-exporter:9113']